<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>Notes</title>
    <script src="https://kit.fontawesome.com/29d094865d.js" crossorigin="anonymous"></script>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Amita|Caveat|Cookie|Courgette|Covered+By+Your+Grace|Dancing+Script|Gloria+Hallelujah|Gochi+Hand|Great+Vibes|Indie+Flower|Kalam|Kaushan+Script|Nanum+Brush+Script|Pacifico|Reenie+Beanie|Satisfy|Shadows+Into+Light" rel="stylesheet">
</head>

<body>
    <div id="root"></div>
    <script src="js/bundle.js"></script>
</body>

</html>