<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Notes</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Amita|Caveat|Cookie|Courgette|Covered+By+Your+Grace|Dancing+Script|Gloria+Hallelujah|Gochi+Hand|Great+Vibes|Indie+Flower|Kalam|Kaushan+Script|Nanum+Brush+Script|Pacifico|Reenie+Beanie|Satisfy|Shadows+Into+Light" rel="stylesheet">
    </head>
    <body>
        <div id="root"></div>
        <script src="js/bundle.js"></script>
    </body>
</html>
