<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>Sticky Notes</title>
    <script src="https://kit.fontawesome.com/29d094865d.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Kalam|Permanent+Marker&display=swap" rel="stylesheet" />
</head>

<body>
    <div id="root"></div>
    <script src="js/bundle.js"></script>
</body>

</html>