<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>Notes</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <style>
        :root {
            --main-color: #0C358C;
            --secondary-color: #395EAB;
            --tertiary-color: #69B7C4;
        }

        html,
        body {
            height: 100%;
            margin: 0;
            position: relative;
            display: block;
            background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('img/login-bg-2.jpeg');
            background-size: cover;
        }

        .login {
            padding: 3em;
        }

        .login .row {
            margin-top: 10em;
        }

        .submit-btn {
            background-color: var(--main-color);
            border-color: var(--main-color);
        }

        .submit-btn:hover {
            background-color: var(--secondary-color);
            border-color: var(--secondary-color);
        }

        .logo {
            font-family: 'Permanent Marker';
        }

        .btn {
            background: none;
            border: none;
            padding: 0;
        }

        .google-signin {
            width: 70%;
        }

        .google-signin--disabled {
            content: url(btn_google_signin_dark_disabled_web@2x.png);
        }
    </style>
</head>

<body>
    <div class="container login">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card shadow-lg">
                    <div class="card-body text-center">
                        <h6 class="text-center">Welcome!</h6>
                        <h1 class="card-title text-center logo">Sticky Notes</h1>
                        <form>
                            <!-- <input type="button" onclick="window.location='<?= $loginUrl ?>'" value="Sign in with Google" class="btn btn-danger"> -->
                            <button type="button" class="btn google-btn"><img class="google-signin" src="img/btn_google_signin_dark_normal_web@2x.png"></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function handleGoogleSignin(event) {
            this.disabled = true;
            window.location = '<?= $loginUrl ?>';
        }

        document.querySelector('.google-btn')
            .addEventListener('click', handleGoogleSignin);
    </script>
</body>

</html>