<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <title>Notes</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Amita|Caveat|Cookie|Courgette|Covered+By+Your+Grace|Dancing+Script|Gloria+Hallelujah|Gochi+Hand|Great+Vibes|Indie+Flower|Kalam|Kaushan+Script|Nanum+Brush+Script|Pacifico|Reenie+Beanie|Satisfy|Shadows+Into+Light" rel="stylesheet">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container" style="margin-top: 100px">
            <div class="row justify-content-center">
                <div class="col-md-6 col-offset-3" a        lign="center">
                    <form>
                        <input placeholder="Email..." name="email" class="form-control"><br>
                        <input type="password" placeholder="Password..." name="password" class="form-control"><br>
                        <input type="button" onclick="window.location='<?= $loginUrl ?>'"  value="Log In with Google" class="btn btn-danger">
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>
